name: CI ZeldaReco

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # O la versione che usi nel tuo ambiente locale

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installa le tue dipendenze (assicurati di avere un file requirements.txt o pyproject.toml)
          pip install -r requirements.txt
          pip install pytest pytest-xdist scipy numba numpy

      - name: Run tests
        run: |
          # Esegue tutti i test in parallelo su tutti i core disponibili in GitHub
          pytest -n auto tests/
