name: CI baorecon
on:
  push:
    branches:
      - main
    paths-ignore:
        - 'README.md'
        - 'docs/**'       # ignora qualsiasi modifica nella cartella docs
        - 'LICENSE'
        - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
        - 'README.md'
        - 'docs/**'       # ignora qualsiasi modifica nella cartella docs
        - 'LICENSE'
        - '.gitignore'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin libfftw3-dev

      - name: Install dependencies
        env:
          MPICC: mpicc
        run: |
          python -m pip install --upgrade pip setuptools wheel

          pip install git+https://github.com/cosmodesi/pyrecon.git@mpi

          # Installa baorecon in modalità editabile insieme ai test requirements
          # (pyproject.toml è l'unica fonte di verità per le dipendenze)
          pip install -e .[test]

      - name: Run tests
        run: |
          # Ora pytest troverà baorecon perché è installato nell'ambiente!
          pytest -n auto tests/
